name: Jacob Fentress
main_css: /css/master.css
exclude: [ README.md ]

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

source:      .
destination: ./_site
layouts:     ./_layouts
exclude:     [ sass, codekit-config.json, README.md, editorially ]

future:      true
show_drafts: nil
limit_posts: 0
pygments:    false

relative_permalinks: false

permalink: /:year/:month/:day/:title
paginate_path: 'page:num'
