name: Jacob Fentress
main_css: /css/master.css
exclude:
    - node_modules
    - Gruntfile.js
    - package.json
    - bower.json
    - README.md
    - TODO.md

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

source:      .
destination: ./_site
layouts:     ./_layouts

future:      true
show_drafts: nil
limit_posts: 0
highlighter: false

relative_permalinks: false

permalink: /:year/:month/:day/:title
paginate_path: 'page:num'
